// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Dialog: typeof import('./src/components/core/dialog.vue')['default']
    DynamicCard: typeof import('./src/components/dynamicCard.vue')['default']
    Edit: typeof import('./src/components/icons/edit.vue')['default']
    HeaderSearch: typeof import('./src/components/layoutComponets/headerSearch.vue')['default']
    Like: typeof import('./src/components/icons/like.vue')['default']
    Like_filled: typeof import('./src/components/icons/like_filled.vue')['default']
    LoginForm: typeof import('./src/components/core/loginForm.vue')['default']
    Logout: typeof import('./src/components/icons/logout.vue')['default']
    MessageQueue: typeof import('./src/components/messageQueue.vue')['default']
    NavBar: typeof import('./src/components/layoutComponets/navBar.vue')['default']
    News: typeof import('./src/components/icons/news.vue')['default']
    NewsList: typeof import('./src/components/layoutComponets/newsList.vue')['default']
    QHeader: typeof import('./src/components/layoutComponets/qHeader.vue')['default']
    QnavBar: typeof import('./src/components/layoutComponets/qnavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/icons/search.vue')['default']
    Start: typeof import('./src/components/icons/start.vue')['default']
    Start_filled: typeof import('./src/components/icons/start_filled.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCountDown: typeof import('vant/es')['CountDown']
    VanDropdownItem: typeof import('vant/es')['DropdownItem']
    VanDropdownMenu: typeof import('vant/es')['DropdownMenu']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanList: typeof import('vant/es')['List']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}
