/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ChatList: typeof import('./../components/message/ChatList.vue')['default']
    HeaderSearch: typeof import('./../components/HeaderSearch.vue')['default']
    LoginForm: typeof import('./../components/core/LoginPopup/LoginForm.vue')['default']
    LoginPopup: typeof import('./../components/core/LoginPopup/index.vue')['default']
    NavBar: typeof import('./../components/navBar.vue')['default']
    Qheader: typeof import('./../components/core/Qheader.vue')['default']
    QHeader: typeof import('./../components/qHeader.vue')['default']
    RegisterForm: typeof import('./../components/core/LoginPopup/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    TabBar: typeof import('./../components/core/TabBar.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCountDown: typeof import('vant/es')['CountDown']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanList: typeof import('vant/es')['List']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
