name: build

on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    env:  
      VITE_BASE_URL: ${{secrets.VITE_BASE_URL}}
      VITE_BASE_URL_WS: ${{secrets.VITE_BASE_URL_WS}}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: "16"
        cache: 'yarn'

    - name: install 
      run: yarn install

    - name: build ...
      run: npm run build
    - name: mv nojekyll
      run: mv .nojekyll /dist
    - uses: actions/configure-pages@v2
    - uses: actions/upload-pages-artifact@v1
      with:
        path: dist
    - name: Deploy
      id: deployment
      uses: actions/deploy-pages@v1