name: build

on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      VITE_BASE_URL: ${{secrets.VITE_BASE_URL}}
      VITE_BASE_URL_WS: ${{secrets.VITE_BASE_URL_WS}}
    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: "16"
        cache: 'yarn'

    - name: install 
      run: yarn install

    - name: build ...
      run: npm run build
    - uses: actions/configure-pages@v2
    - uses: actions/upload-pages-artifact@v1
      with: dist
    - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1