name: branches-sync

on:
  # 自动同步，每 6 小时执行一次
  schedule:
    - cron: '0 */6 * * *'
  # 手动触发部署
  workflow_dispatch:

jobs:
  sync-to-gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:hooray/fantastic-startkit.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:hooray/fantastic-startkit.git
